name: Get sing-box releases
permissions: write-all
on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 16 * * *'  

jobs:
  monitor_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  

      - name: Get sing-box latest version
        run: |
          latest_tag=$(curl -sSL https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.tag_name' | tr -d "v")
          echo "Latest version: $latest_tag" 
          if [[ "$latest_tag" != "$(cat version)" ]];then
            echo "$latest_tag" > version 
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add version
            git commit -m "Update version file with latest sing-box version"
            git push
          else
            exit 0

